LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := spdlog
LOCAL_CATEGORY_PATH := libs
LOCAL_DESCRIPTION := Fast c++ logging library
LOCAL_CATEGORY_PATH := libs
LOCAL_ARCHIVE_VERSION := 1.17.0
LOCAL_ARCHIVE := $(LOCAL_MODULE)-$(LOCAL_ARCHIVE_VERSION).tar.gz
LOCAL_ARCHIVE_SUBDIR := $(LOCAL_MODULE)-$(LOCAL_ARCHIVE_VERSION)

LOCAL_CXXFLAGS := -DSPDLOG_SHARED_LIB -DFMT_SHARED -DSPDLOG_COMPILED_LIB
LOCAL_EXPORT_LDLIBS := -lspdlog -pthread
LOCAL_EXPORT_C_INCLUDES := $(TARGET_OUT_STAGING)/usr/include

include $(BUILD_CMAKE)
